version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000" # Map localhost:8000 -> container:8000
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"     # Map localhost:80 -> container:80
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000 # <- MAGIC! 'backend' is the hostname of the other container
    depends_on:
      - backend